### ISSUE TITLE
Switch example - button stops working if pressed shortly after boot (MEGH-2945)

### ISSUE THREAD

**Issue by miroslavpetrov** [espressif/esp-rainmaker#100]
**Steps to reproduce the issue:**
Setup:
Module used: ESP32-C3-mini-1
ESP IDF version: 4.3.1
Code: Switch example without any modifications

Problem: 
If the button connected to GPIO9 is pressed sometime during the first 10 seconds after power up(during WiFi connection, MQTT connection and starting work queues) the first event is registered and the switch is turned on **but each subsequent press is not being registered.** Its important to note that the switch can be controlled by the smartphone app. 

I guess the button handler just stops working forever(until reboot) if the button is pressed during some cpu intensive tasks.

I have noticed similar behaviour with more complex firmware where I read energy measurement IC and temperature sensor over I2C. When I schedule sensor readings with freertos software timer and I press the button during the execution of the timer's callback function the button stops working forever(until reboot) again.

I fixed the above issue by using esp_timer instead. Now if I press the button during the execution of the timer's callback function the issue is not showing.

Any ideas?

**Comment by shixinke-orion** [comment]
Hi Miroslav, Could you try to modify the priority and queue length of the freertos timer to solve this issue? The button component of rainmaker uses a lot of callbacks, but they are not handled well. I guess the stop work is related to this.
```
(Top) → Component config → FreeRTOS
(6) FreeRTOS timer task priority
(20) FreeRTOS timer queue length
```

**Comment by miroslavpetrov** [comment]
This fixes the issue for now. Thanks.
