### ISSUE TITLE
How to check if device is connected to server (MEGH-3684)

### ISSUE THREAD

**Issue by SubhodipRoy161101** [espressif/esp-rainmaker#145]
I would like to know which function would tell us if the device is connected to the cloud or not. It would simply check if esp32 is connected to the cloud and return true if it is connected and return false if it is not connected.

**Comment by shahpiyushv** [comment]
@SubhodipRoy161101 , there is no API that gives this information directly, but your application code can use the RMAKER_MQTT_EVENT_CONNECTED  and RMAKER_MQTT_EVENT_DISCONNECTED  events to track the connectivity as you can see [here](https://github.com/espressif/esp-rainmaker/blob/5c81ecf755432ebeffaadc966b67799ea2f7c9d3/examples/switch/main/app_main.c#L83).
