### ISSUE TITLE
SoftAP vs BLE provisioning (MEGH-3697)

### ISSUE THREAD

**Issue by jacek12345** [espressif/esp-rainmaker#149]
What to consider when choosing?
Is any of the methods better? Or depends from something?
Using ESP32C3

**Comment by shahpiyushv** [comment]
@jacek12345 , generally we recommend using BLE so that the phone does not have to disconnect from its existing Wi-Fi network just for provisioning. Moreover, we have noticed that some phones automatically disconnect from the SoftAP interface since that network does not have Internet.

**Comment by jacek12345** [comment]
Thank You for response.
