### ISSUE TITLE
Adding new parameter after esp_rmaker_start() (MEGH-3814)

### ISSUE THREAD

**Issue by jacek12345** [espressif/esp-rainmaker#166]
What is the proper way for adding new parameter for device "on-the-fly"?
I need to add parameter and want see this param in mobile app.

**Comment by shahpiyushv** [comment]
@jacek12345 If you add a new parameter, you can call the `esp_rmaker_report_node_details()` API to report the new config and param value to the RainMaker backend. However, you will need to refresh the phone app for the new parameter to reflect.

**Comment by jacek12345** [comment]
1. esp_rmaker_param_create()
2. esp_rmaker_param_add_ui_type()
3. esp_rmaker_device_add_param()
4. esp_rmaker_param_update_and_report()
5. esp_rmaker_report_node_details()
Is it good way or something wrong/unnecessary?

**Comment by shahpiyushv** [comment]
Step 4 is not required, since `esp_rmaker_report_node_details()` will report all params. Rest all is fine.

**Comment by jacek12345** [comment]
Thank You
