### ISSUE TITLE
Build Issue (MEGH-1098)

### ISSUE THREAD

**Issue by intothefuture20** [espressif/esp-rainmaker#17]
Not able to build example - Switch and Fan, did not try others. I get the following error in both:

![Error-Part1](https://user-images.githubusercontent.com/36773209/89291028-6c05e780-d677-11ea-9f88-aadc1f8c04a0.PNG)
![Error-Part2](https://user-images.githubusercontent.com/36773209/89291031-6d371480-d677-11ea-9159-71f40af64a0d.PNG)

Seems something wrong in led_strip under components.

**Comment by shahpiyushv** [comment]
@intothefuture20 , I suppose you are using esp-idf v4.0 or v4.1. Can you try with the master branch?

**Comment by intothefuture20** [comment]
I tried the master branch and got another error now:

![image](https://user-images.githubusercontent.com/36773209/89300215-7c24c380-d685-11ea-8440-d335590a0e42.png)

and similarly for switch.elf

**Comment by shahpiyushv** [comment]
@intothefuture20 , the log is insufficient to understand what is going wrong. A few questions:
- Did you try an `idf.py fullclean` before rebuilding after you switched the branches? I would also recommend that you delete the sdkconfig file before rebuilding.
- Are you able to build other esp-idf examples on the master branch?

**Comment by intothefuture20** [comment]
Hello Piyush,

May be off the league question, but are there other ways to build the examples? I mean the easier one maybe, easier method?

And yes I was able to build esp-idf examples without any error

**Comment by intothefuture20** [comment]
Hello Piyush,

Thank you for your help. Much appreciated. As suggested deleting sdkconfig file helped and the build was successful.

**Comment by shahpiyushv** [comment]
@intothefuture20 , good to know that the problem got fixed. If you prefer IDEs, we have a [VS Code extension](https://github.com/espressif/vscode-esp-idf-extension) available for esp-idf. You can also check the [RainMaker Support](https://github.com/espressif/vscode-esp-idf-extension#esp-rainmaker-support) section there.

**Comment by shahpiyushv** [comment]
Closing this issue as it has been resolved.
