### ISSUE TITLE
Confirming Node Association Failed (MEGH-3924)

### ISSUE THREAD

**Issue by UserOfSpace** [espressif/esp-rainmaker#189]
How do I fix?

**Comment by shahpiyushv** [comment]
@UserOfSpace , do you see your device crashing and rebooting during provisioning? If yes, please `#include <wifi_provisioning/manager.h>` in your code and add this into the [event handler](https://github.com/espressif/arduino-esp32/blob/master/libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino#L28)

```
  switch (sys_event->event_id) {
    case ARDUINO_EVENT_PROV_INIT:
      wifi_prov_mgr_disable_auto_stop(10000);
      break;
    case ARDUINO_EVENT_PROV_CRED_SUCCESS:
      Serial.println("Stopping Provisioning!!!");
      wifi_prov_mgr_stop_provisioning();
      break;
```

**Comment by UserOfSpace** [comment]
> @UserOfSpace , do you see your device crashing and rebooting during provisioning? If yes, please `#include <wifi_provisioning/manager.h>` in your code and add this into the [event handler](https://github.com/espressif/arduino-esp32/blob/master/libraries/RainMaker/examples/RMakerSwitch/RMakerSwitch.ino#L28)
> 
> ```
>   switch (sys_event->event_id) {
>     case ARDUINO_EVENT_PROV_INIT:
>       wifi_prov_mgr_disable_auto_stop(10000);
>       break;
>     case ARDUINO_EVENT_PROV_CRED_SUCCESS:
>       Serial.println("Stopping Provisioning!!!");
>       wifi_prov_mgr_stop_provisioning();
>       break;
> ```
> 

.

**Comment by anjalir14** [comment]
I'm having the same issue but my device is not crashing and rebooting it's just not able to connect with mqtt.
