### ISSUE TITLE
Support HOMEKIT (MEGH-1226)

### ISSUE THREAD

**Issue by exrector** [espressif/esp-rainmaker#19]
The author of this post ( https://www.esp32.com/viewtopic.php?t=17054 ) did not make a request.  I will do.  we are all looking forward to apple homekit support and will be happy to participate in the beta.

**Comment by shahpiyushv** [comment]
@exrector , we have now opened up the [ESP HomeKit SDK](https://github.com/espressif/esp-homekit-sdk) and added an example for [RainMaker + HomeKit](https://github.com/espressif/esp-rainmaker/tree/master/examples/homekit_switch) integration.

**Comment by shahpiyushv** [comment]
Closing this issue since it has been addressed.
