### ISSUE TITLE
There is issue if call nvs_set_xx and without call function nvs_commit (MEGH-4019)

### ISSUE THREAD

**Issue by pnt325** [espressif/esp-rainmaker#196]
I have take a a look about the [esp_schedule_nvs.c](https://github.com/espressif/esp-rainmaker/blob/master/components/esp_schedule/src/esp_schedule_nvs.c) all the function set value to nvs without call `nvs_commit` while the api document mention should be call to  actual storage.

**Comment by shahpiyushv** [comment]
Thanks for reporting this. We will fix this soon. Meanwhile, note that this nvs usage is disabled by default, and instead we use Rainmaker persistent parameters to ensure that the schedules stay active even across reboots.
