### ISSUE TITLE
E (376645) esp_mqtt_glue: MQTT_EVENT_ERROR E (391653) esp-tls: couldn't get hostname for :a1p72mufdu6064-ats.iot.us-east-1.amazonaws.com: getaddrinfo() returns 202, addrinfo=0x0 E (391653) esp-tls: Failed to open new connection E (391658) TRANSPORT_BASE: Failed to open a new connection E (391663) MQTT_CLIENT: Error transport connect E (391667) esp_mqtt_glue: MQTT_EVENT_ERROR MQTT_CLIENT: Error transport connect E (391667) esp_mqtt_glue: MQTT_EVENT_ERROR

### ISSUE THREAD

**Issue by Sanju340** [espressif/esp-rainmaker#199]

**Comment by shahpiyushv** [comment]
@Sanju340 , from the message, it seems to be some local network issue since the esp could not even get the host name. Meanwhile, it would have been nicer if the title was concise and precise and the logs and other details were mentioned neatly in the description :)

**Comment by Sanju340** [comment]
MQTT_EVENT_ERROR 
E (391658) TRANSPORT_BASE: Failed to open a new
E (391667) esp_mqtt_glue:

**Comment by shahpiyushv** [comment]
Closing this because of insufficient information.
