### ISSUE TITLE
Question:Rainmaker support (MEGH-789)

### ISSUE THREAD

**Issue by abhatikar** [espressif/esp-rainmaker#2]
Will we have Rainmaker support for the Esp32 Wroom or Huzzah32 ?

**Comment by shahpiyushv** [comment]
We will start giving out support for ESP32 on-demand and later open up to a wider audience. Can you send the email id you used for registering on ESP RainMaker to esp-rainmaker-admin@espressif.com so that it can be enabled for you?

**Comment by DanielJimenezHernandez** [comment]
same issue here i want to start testing in the platform with the devkit-c that i have can this also be enabled for me?

**Comment by Di-Strix** [comment]
Not so long ago, I tested Rainmaker again on esp-wroom-32 and after the update it started working fine. But it needs to setup CLI first

**Comment by shahpiyushv** [comment]
@DanielJimenezHernandez , the ESP32 support is now enabled by default for all. As mentioned by  @Di-Strix , you need to set-up the CLI and use the claim command to get the credentials.

**Comment by shahpiyushv** [comment]
Closing this issue as it is no more relevant.
