### ISSUE TITLE
Phone app is crashing on IOS after latest update.  (MEGH-1231)

### ISSUE THREAD

**Issue by chadburnett** [espressif/esp-rainmaker#20]
Is anyone else getting this?  I tried to delete the app and reinstall but it still launches and then crashes right away.

**Comment by vikas-chandra-mnnit** [comment]
Hi @chadburnett, We have also experienced this issue on our end and have made the required fix. We are in the process of releasing the updated app on App Store. We will notify you once the new version is live.

**Comment by chadburnett** [comment]
Outstanding work @vikas-chandra-mnnit!  Thanks for the heads up.

**Comment by vikas-chandra-mnnit** [comment]
@chadburnett A new version of RainMaker App with the above fix is now available on App Store.

**Comment by shahpiyushv** [comment]
Closing this issue since the fix has been provided.
