### ISSUE TITLE
How to get ESP.LOGI  logs on insights (MEGH-4101)

### ISSUE THREAD

**Issue by Jo14532** [espressif/esp-rainmaker#207]
I managed to flash my ESP32 MCU with the switch example and also included the insight feature.

However I see I only get logs for the ESP.LOGE() function. I do not see any logs for my ESP.LOGI() function.

How do I get logs onto insights for my ESP.LOGI() function?

**Comment by vikramdattu** [comment]
Hi @Jo14532 since LOGI are too verbose, we have kept those to be not reported. You may however use `ESP_DIAG_EVENT` to achieve the same.

**Comment by shahpiyushv** [comment]
Closing this issue since it has been answered.
