### ISSUE TITLE
how to create my own rainmaker cloud? (MEGH-4106)

### ISSUE THREAD

**Issue by thuanpv1** [espressif/esp-rainmaker#209]
Hello masters, 

I just want to ask if there is a way to clone ESP rainmaker cloud to my machine and run it localy? I read somewhere on internet that the ESP rainmaker cloud is open source, but I cannot find its source code. Please help.
(this is just a question not an issue, but not find where to change the issue type, so i just submit as an issue)

Regards,
Thuan

**Comment by sanketwadekar** [comment]
Hi,
The Rainmaker Agent is open-source, whereas the Rainmaker Cloud is not. It is available to use for free for educational/hobby purposes. You can get in touch with our sales team at [sales@espressif.com](mailto:sales@espressif.com) for details about private deployments.

Thanks

**Comment by shahpiyushv** [comment]
Closing this issue because it has been answered.
