### ISSUE TITLE
Adding Devices  (MEGH-4108)

### ISSUE THREAD

**Issue by MadanMeelan** [espressif/esp-rainmaker#210]
How many devices can we add in Rainmaker app for free, I need to test 8 devices for complete home, can we add all 8 devices through public platform? Please help me on this...

**Comment by sanketwadekar** [comment]
Hello,
Public RainMaker has a default quota limit of 5, which we can increase based on user requirements only for hobby/evaluation purposes.
If you have reached your quota, you can get it increased by sending an email to [esp-rainmaker-admin@espressif.com](mailto:esp-rainmaker-admin@espressif.com)

**Comment by MadanMeelan** [comment]
Can we increase it to 8 devices? Is there any time limit for the devices which were added in public Rainmaker app?

**Comment by MadanMeelan** [comment]
Hello,

How much time it'll take to extend the device count after sending the
request? One more question, is there any duration limit for the devices
which were added to the public Rainmaker app? Please let me know.

Regards
Madan Mohan Reddy

**Comment by MadanMeelan** [comment]
I'm practicing it for my house as a hobby, please let me know

**Comment by shahpiyushv** [comment]
@MadanMeelan , increasing the quota doesn't take much time. Just send a request to [esp-rainmaker-admin@espressif.com](mailto:esp-rainmaker-admin@espressif.com) as mentioned [above](https://github.com/espressif/esp-rainmaker/issues/210#issuecomment-1360917854). 

Meanwhile, there is no specific expiry for the devices added to public RainMaker.

**Comment by JohnMacrae** [comment]
Hi Piyush - season's greetings :)

At this point I think it might be worth clarifying that the limit is on
physical devices (ESP32) rather than the number of (household) devices
driven from one ESP32?

Kind Regards
John

**Comment by shahpiyushv** [comment]
@JohnMacrae , thanks for raising this point :). Indeed, this limit is on the number of nodes (physical ESP32s) and not the number of devices. A single ESP32 [node](https://rainmaker.espressif.com/docs/spec-concepts.html#node) can have [multiple devices](https://rainmaker.espressif.com/docs/spec-concepts.html#devices). Moreover, this is applicable only for host/assisted claiming (which are the only options if you are using ESP32 anyways). For ESP32C3, ESP32S2 and ESP32S3, if you use self claiming, then this quota limit does not apply.

**Comment by MadanMeelan** [comment]
@Piyush what does it mean Self claiming? As I'm starting please explain

**Comment by shahpiyushv** [comment]
@MadanMeelan , you can read more about various types of claiming [here](https://rainmaker.espressif.com/docs/claiming.html).

**Comment by shahpiyushv** [comment]
Closing this issue since it has been answered.
