### ISSUE TITLE
IDF 4.4 compatibility problem (MEGH-4130)

### ISSUE THREAD

**Issue by eos1d3** [espressif/esp-rainmaker#215]
With latest ESP IDF 4.4,  any IDF commands: `set-target`, `build`, `menuconfig`, will cause error. Examples used are `switch` and `led_light`.

```
4 problems were found in the manifest file /Users/user1/esp/esp-rainmaker/components/esp_rainmaker/idf_component.yml:
Invalid manifest format
Invalid dependency format
Dependency version spec format is invalid
Unknown keys in dependency details: rules
CMake Error at /Users/user1/esp/esp-idf/tools/cmake/build.cmake:452 (message):
Call Stack (most recent call first):
  /Users/user1/esp/esp-idf/tools/cmake/project.cmake:384 (idf_build_process)
  CMakeLists.txt:16 (project)


-- Configuring incomplete, errors occurred!
```

**Comment by shahpiyushv** [comment]
@eos1d3 , can you upgrade your idf component manager using `pip install --upgrade idf-component-manager` and retry?

**Comment by eos1d3** [comment]
Hi, just tested with the above command, it fixes the problem now. Why is the command needed as other IDF versions do not need it?

**Comment by shahpiyushv** [comment]
@eos1d3 ESP IDF versions before v4.4 do not use component manager by default and hence, the manifest file gets ignored. idf v5.0 already has the latest component manager python package and so, that too works fine. v4.4 had some changes that caused these failures and they were eventually fixed after the release, hence the issues and the requirement if manually updating it.

**Comment by eos1d3** [comment]
Thanks for your help!
