### ISSUE TITLE
Problem with assisted claiming (MEGH-4148)

### ISSUE THREAD

**Issue by jacek12345** [espressif/esp-rainmaker#219]
Is it normal that each started claiming changes NodeID?
![image](https://user-images.githubusercontent.com/34368502/210232658-5a403dc1-1924-46c9-ad72-66df0430eedd.png)

Is this NodeID changing the reason of Claiming abort "User does not have available quota"?

The problem started today after added to my code:
- erasing of user data nvs partition and factory reset:
err = nvs_flash_erase_partition_ptr("devdata");
factory_reset_trigger(NULL);

- added some data to this partition
- made "erase-flash"
After that, my iOS app shows something with BLE and suggest to restart device
After that, there is  "User does not have available quota" in app
Also see that each try changes NodeID.

I can back to Self Claiming but can't use OTA and Insights in this situation, right?
Also question What after private deploy? As i understand there is not claiming process (will set "Do not use claiming" in menu config) and it will not have issue with OTA nor Insights? If it is true, then i can stay with self claiming while working with public deploy. Will develope OTA and Insights after switch to private deploy.

**Comment by shahpiyushv** [comment]
@jacek12345 , with assisted claiming, for the same mac address + user id combination, the same node id gets assigned. However, the code flow is such that it first reads the node id (which is equal to mac address if a valid one is not found in nvs) and then that is used for the claiming. In your case, some node id is found in nvs and so that is getting used for claiming instead of the mac address, resulting into a new node id getting assigned. Erasing the fctry partition should resolve this issue.

Meanwhile, recently we made a change such that even for self claiming, the primary end user is made the admin. So, you can also use self claiming.

Your understanding about the private deployment is correct. There is no claiming, but the node registration process ensures that you have admin access to the node.

**Comment by jacek12345** [comment]
> Meanwhile, recently we made a change such that even for self claiming, the primary end user is made the admin. So, you can also use self claiming.

Do You mean that it is possible now to use Self Claiming and see node in dashboards?

**Comment by shahpiyushv** [comment]
> Do You mean that it is possible now to use Self Claiming and see node in dashboards?

Yes

**Comment by jacek12345** [comment]
1. Indeed, I see data coming from node in ESP Insights Dashboard but node status on the node list is "unknown".
2. I can't see node in ESP RainMaker Dashboard

**Comment by shahpiyushv** [comment]
@jacek12345 , can you share the node id for this latest issue you mentioned about node visible in Insights, but not on RainMaker dashboard?

**Comment by jacek12345** [comment]
it is node: A0764E5AE100. It is ESP32-C3. I see this with unknown state but data comes:
![image](https://user-images.githubusercontent.com/34368502/212259255-838cb20e-4f8b-470c-920a-6ccb8adfd8f5.png)
![image](https://user-images.githubusercontent.com/34368502/212259348-8a01439c-4976-4fd6-858e-1ad2d69a35fe.png)

Can't see in RainMaker dashboard:
![image](https://user-images.githubusercontent.com/34368502/212259550-11ad4339-79ba-48b0-8aeb-251673b67d0b.png)

Now I use ESP32-S3 module and can't see node in Insights nor RainMaker dashboard. Is something more to do with S3 module?

**Comment by jacek12345** [comment]
Still can't see my S3 device in RainMaker dashboard nor ESP Insights dashboard.

```
I (24) boot: ESP-IDF v4.4.3 2nd stage bootloader
I (25) boot: compile time 08:54:37
I (25) boot: chip revision: 0
I (26) boot.esp32s3: Boot SPI Speed : 80MHz
I (31) boot.esp32s3: SPI Mode       : DIO
I (36) boot.esp32s3: SPI Flash Size : 8MB
I (40) boot: Enabling RNG early entropy source...
I (46) boot: Partition Table:
I (49) boot: ## Label            Usage          Type ST Offset   Length
I (57) boot:  0 sec_cert         unknown          3f 06 0000d000 00003000
I (64) boot:  1 nvs              WiFi data        01 02 00010000 00006000
I (72) boot:  2 otadata          OTA data         01 00 00016000 00002000
I (79) boot:  3 phy_init         RF data          01 01 00018000 00001000
I (87) boot:  4 ota_0            OTA app          00 10 00020000 003c0000
I (94) boot:  5 ota_1            OTA app          00 11 003e0000 003c0000
I (102) boot:  6 fctry            WiFi data        01 02 007a0000 00006000
I (109) boot:  7 devdata          WiFi data        01 02 007a6000 00003000
I (117) boot:  8 coredump         Unknown data     01 03 007a9000 00010000
I (124) boot: End of partition table
I (129) esp_image: segment 0: paddr=00020020 vaddr=3c0f0020 size=3ed3ch (257340) map
I (183) esp_image: segment 1: paddr=0005ed64 vaddr=3fc9a180 size=012b4h (  4788) load
I (185) esp_image: segment 2: paddr=00060020 vaddr=42000020 size=eae84h (962180) map
I (361) esp_image: segment 3: paddr=0014aeac vaddr=3fc9b434 size=03818h ( 14360) load
I (365) esp_image: segment 4: paddr=0014e6cc vaddr=40374000 size=1617ch ( 90492) load
I (387) esp_image: segment 5: paddr=00164850 vaddr=50000000 size=00010h (    16) load
I (396) boot: Loaded app from partition at offset 0x20000
I (396) boot: Disabling RNG early entropy source...
I (408) cpu_start: Pro cpu up.
I (408) cpu_start: Starting app cpu, entry point is 0x40375444
0x40375444: call_start_cpu1 at F:/GitHub/esp-idf-v4.4.3/components/esp_system/port/cpu_start.c:148

I (0) cpu_start: App cpu up.
I (422) cpu_start: Pro cpu start user code
I (422) cpu_start: cpu freq: 160000000
I (422) cpu_start: Application information:
I (425) cpu_start: Project name:     proiot1
I (430) cpu_start: App version:      1.1
I (434) cpu_start: Compile time:     Jan 13 2023 10:36:58
I (440) cpu_start: ELF file SHA256:  d19723f5b3afc189...
I (446) cpu_start: ESP-IDF:          v4.4.3
I (451) heap_init: Initializing. RAM available for dynamic allocation:
I (458) heap_init: At 3FCA63F8 len 00043318 (268 KiB): D/IRAM
I (465) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
I (472) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (478) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (485) spi_flash: detected chip: generic
I (489) spi_flash: flash io: dio
I (493) sleep: Configure to isolate all GPIO pins in sleep state
I (500) sleep: Enable automatic switching of GPIO sleep configuration
I (507) coexist: coexist rom version e7ae62f
I (512) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (10) esp_rmaker_console: Initialising UART on port 0
I (532) esp_rmaker_commands: Registering command: up-time
I (532) uart: queue free spaces: 8
I (542) esp_rmaker_commands: Registering command: mem-dump
I (552) esp_rmaker_commands: Registering command: task-dump
I (552) esp_rmaker_commands: Registering command: cpu-dump
I (562) esp_rmaker_commands: Registering command: sock-dump
I (572) esp_rmaker_commands: Registering command: heap-trace
I (572) esp_rmaker_commands: Registering command: reset-to-factory
I (582) esp_rmaker_commands: Registering command: add-user
I (592) esp_rmaker_commands: Registering command: get-node-id
I (592) esp_rmaker_commands: Registering command: wifi-prov
I (602) esp_rmaker_commands: Registering command: local-time
I (602) esp_rmaker_commands: Registering command: tz-set
I (612) esp_rmaker_commands: Registering command: cmd
I (622) gpio: GPIO[2]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3
E (632) gpio: gpio_install_isr_service(449): GPIO isr service already installed
I (632) gpio: GPIO[4]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3
I (642) gpio: GPIO[7]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (652) gpio: GPIO[18]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (662) led_serv: BLE led initialise...
I (672) gpio: GPIO[1]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (672) led_serv: BLE led initialise...
I (682) gpio: GPIO[11]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (692) led_serv: BLE led initialise...
I (692) gpio: GPIO[19]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (702) led_serv: BLE led initialise...
I (712) gpio: GPIO[10]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (722) led_serv: BLE led initialise...
I (722) gpio: GPIO[6]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
W (792) app_main: reading configuration from NVS
W (792) app_main: reading end
I (792) pp: pp rom version: e7ae62f
I (792) net80211: net80211 rom version: e7ae62f
I (802) wifi:wifi driver task: 3fcf7208, prio:23, stack:6656, core=0
I (802) system_api: Base MAC address is not set
I (802) system_api: read default base MAC address from EFUSE
I (832) wifi:wifi firmware version: 8cb87ff
I (832) wifi:wifi certification version: v7.0
I (832) wifi:config NVS flash: enabled
I (832) wifi:config nano formating: disabled
I (832) wifi:Init data frame dynamic rx buffer num: 32
I (842) wifi:Init management frame dynamic rx buffer num: 32
I (842) wifi:Init management short buffer num: 32
I (852) wifi:Init dynamic tx buffer num: 32
I (852) wifi:Init static tx FG buffer num: 2
I (862) wifi:Init static rx buffer size: 1600
I (862) wifi:Init static rx buffer num: 10
I (862) wifi:Init dynamic rx buffer num: 32
I (872) wifi_init: rx ba win: 6
I (872) wifi_init: tcpip mbox: 32
I (882) wifi_init: udp mbox: 6
I (882) wifi_init: tcp mbox: 6
I (882) wifi_init: tcp tx win: 5744
I (892) wifi_init: tcp rx win: 5744
I (892) wifi_init: tcp mss: 1440
I (902) wifi_init: WiFi IRAM OP enabled
I (902) wifi_init: WiFi RX IRAM OP enabled
I (922) esp_rmaker_work_queue: Work Queue created.
I (942) esp_mqtt_glue: AWS PPI: ?Platform=APN3|A0|RM|EX00|RMDev|1x0|7CDFA1E25EA0
I (942) esp_mqtt_glue: Initialising MQTT
I (942) esp_rmaker_mqtt_budget: MQTT Budgeting initialised. Default: 100, Max: 1024, Revive count: 1, Revive period: 5
I (952) app_main: RainMaker Initialised.
I (952) esp_rmaker_node: Node ID ----- 7CDFA1E25EA0
E (962) gpio: gpio_install_isr_service(449): GPIO isr service already installed
I (972) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3
I (1062) esp_rmaker_ota_using_topics: OTA enabled with Topics
I (1072) esp_rmaker_ota: OTA state = 2
I (1072) esp_rmaker_time_service: Time service enabled
I (1082) esp_rmaker_time: Initializing SNTP. Using the SNTP server: pool.ntp.org
W (1092) app_insights: Nodes with Self Claiming may not be accessible for Insights.
I (1102) esp_insights: =========================================
I (1102) esp_insights: Insights enabled for Node ID 7CDFA1E25EA0
I (1112) esp_insights: =========================================
I (1112) esp_rmaker_core: Starting RainMaker Work Queue task
I (1122) esp_rmaker_work_queue: RainMaker Work Queue task started.
W (1122) BT_INIT: esp_bt_mem_release not implemented, return OK
I (1132) wifi_prov_scheme_ble: BT memory released
I (1142) app_wifi: Already provisioned, starting Wi-Fi STA
W (1152) BT_INIT: esp_bt_mem_release not implemented, return OK
I (1152) wifi_prov_scheme_ble: BTDM memory released
I (1162) esp_rmaker_local: Event 6
I (1162) phy_init: phy_version 503,13653eb,Jun  1 2022,17:47:08
I (1212) wifi:mode : sta (7c:df:a1:e2:5e:a0)
I (1212) wifi:enable tsf
I (1212) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
I (1222) wifi:state: init -> auth (b0)
I (1222) wifi:state: auth -> assoc (0)
I (1222) wifi:state: assoc -> run (10)
W (1232) wifi:<ba-add>idx:0 (ifx:0, 70:f3:5a:74:6a:fd), tid:0, ssn:0, winSize:64
I (1252) wifi:connected with Network_wifi, aid = 4, channel 1, BW20, bssid = 70:f3:5a:74:6a:fd
I (1252) wifi:security: WPA2-PSK, phy: bgn, rssi: -41
I (1262) wifi:pm start, type: 1

I (1262) wifi:set rx beacon pti, rx_bcn_pti: 14, bcn_timeout: 14, mt_pti: 25000, mt_time: 10000
I (1292) wifi:BcnInt:102400, DTIM:1
I (2292) app_wifi: Connected with IP Address:10.10.10.134
I (2292) esp_netif_handlers: sta ip: 10.10.10.134, mask: 255.255.255.0, gw: 10.10.10.1
I (2292) esp_rmaker_local: Starting ESP Local control with HTTP Transport and security version: 1
I (2322) esp_https_server: Starting server
I (2322) esp_https_server: Server listening on port 8080
I (2322) esp_rmaker_local: esp_local_ctrl service started with name : 7CDFA1E25EA0
W (2332) app_main: Unhandled RainMaker Event: 6
I (2342) esp_mqtt_glue: Connecting to a1p72mufdu6064-ats.iot.us-east-1.amazonaws.com
I (2342) esp_rmaker_core: Waiting for MQTT connection
I (2822) esp-x509-crt-bundle: Certificate validated
I (3232) esp_rmaker_time: SNTP Synchronised.
I (3232) esp_rmaker_time: The current time is: Mon Jan 16 08:26:18 2023 +0100[CET], DST: No.
I (4472) esp_mqtt_glue: MQTT Connected
I (4472) app_main: MQTT Connected.
I (4472) esp_rmaker_node_config: Reporting Node Configuration of length 5308 bytes.
I (4792) esp_rmaker_param: Params MQTT Init done.
I (4792) esp_rmaker_param: Reporting params (init): {"Brama":{"Name":"OUT1","Stan":0},"Furtka":{"Name":"OUT2","Stan":0,"Czas [s]":3},"Przycisk":{"Name":"INPUT","Stan":"ON","Min. czas pobudzenia [s]":0,"Powiadom gdy aktywne":false,"Powiadom gdy nieaktywne":false,"Odwroc logike":false},"MENU_SCAN":{"Wykryj nowe czujniki":false,"Usun wszystkie czujniki":false},"MENU_NODE":{"Nazwa urzadzenia":"Receiver","Ukryj komponent OUT 1":false,"Ukryj komponent OUT 2":false,"Ukryj komponent IN 1":false,"Zezw. użytk. na edycję":false},"SSDB6B0C232F46":{"Name":"Sensor(2F46)","Stan":"--","Wersja firmware":"--","MAC":"DB:6B:0C:23:2F:46","Model":"SNX-S-1","Bateria [%]":"--","Powiadom gdy ON":false,"Powiadom gdy OFF":false,"Usun ten czujnik":false,"Ukryj akcesorium":false},"Time":{"TZ":"Europe/Warsaw","TZ-POSIX":"CET-1CEST,M3.5.0,M10.5.0/3"},"Schedule":{"Schedules":[]},"Scenes":{"Scenes":[]},"Local Control":{"POP":"b167c722","Type":1}}
I (4882) esp_rmaker_cmd_resp: Enabling Command-Response Module.
I (4882) esp_rmaker_ota_using_topics: Subscribing to: node/7CDFA1E25EA0/otaurl
I (4892) esp_insights: Scheduling Insights timer for 60 seconds.
I (4992) app_main: MQTT Published. Msg id: 2812.
I (5392) app_main: MQTT Published. Msg id: 23420.
I (5392) app_main: MQTT Published. Msg id: 18803.
I (9892) esp_rmaker_ota_using_topics: Fetching OTA details, if any.
I (10182) app_main: MQTT Published. Msg id: 62926.
```

**Comment by sanketwadekar** [comment]
> Still can't see my S3 device in RainMaker dashboard nor ESP Insights dashboard. Using SelfClaiming.
> 
> ```
> I (24) boot: ESP-IDF v4.4.3 2nd stage bootloader
> I (25) boot: compile time 08:54:37
> I (25) boot: chip revision: 0
> I (26) boot.esp32s3: Boot SPI Speed : 80MHz
> I (31) boot.esp32s3: SPI Mode       : DIO
> I (36) boot.esp32s3: SPI Flash Size : 8MB
> I (40) boot: Enabling RNG early entropy source...
> I (46) boot: Partition Table:
> I (49) boot: ## Label            Usage          Type ST Offset   Length
> I (57) boot:  0 sec_cert         unknown          3f 06 0000d000 00003000
> I (64) boot:  1 nvs              WiFi data        01 02 00010000 00006000
> I (72) boot:  2 otadata          OTA data         01 00 00016000 00002000
> I (79) boot:  3 phy_init         RF data          01 01 00018000 00001000
> I (87) boot:  4 ota_0            OTA app          00 10 00020000 003c0000
> I (94) boot:  5 ota_1            OTA app          00 11 003e0000 003c0000
> I (102) boot:  6 fctry            WiFi data        01 02 007a0000 00006000
> I (109) boot:  7 devdata          WiFi data        01 02 007a6000 00003000
> I (117) boot:  8 coredump         Unknown data     01 03 007a9000 00010000
> I (124) boot: End of partition table
> I (129) esp_image: segment 0: paddr=00020020 vaddr=3c0f0020 size=3ed3ch (257340) map
> I (183) esp_image: segment 1: paddr=0005ed64 vaddr=3fc9a180 size=012b4h (  4788) load
> I (185) esp_image: segment 2: paddr=00060020 vaddr=42000020 size=eae84h (962180) map
> I (361) esp_image: segment 3: paddr=0014aeac vaddr=3fc9b434 size=03818h ( 14360) load
> I (365) esp_image: segment 4: paddr=0014e6cc vaddr=40374000 size=1617ch ( 90492) load
> I (387) esp_image: segment 5: paddr=00164850 vaddr=50000000 size=00010h (    16) load
> I (396) boot: Loaded app from partition at offset 0x20000
> I (396) boot: Disabling RNG early entropy source...
> I (408) cpu_start: Pro cpu up.
> I (408) cpu_start: Starting app cpu, entry point is 0x40375444
> 0x40375444: call_start_cpu1 at F:/GitHub/esp-idf-v4.4.3/components/esp_system/port/cpu_start.c:148
> 
> I (0) cpu_start: App cpu up.
> I (422) cpu_start: Pro cpu start user code
> I (422) cpu_start: cpu freq: 160000000
> I (422) cpu_start: Application information:
> I (425) cpu_start: Project name:     proiot1
> I (430) cpu_start: App version:      1.1
> I (434) cpu_start: Compile time:     Jan 13 2023 10:36:58
> I (440) cpu_start: ELF file SHA256:  d19723f5b3afc189...
> I (446) cpu_start: ESP-IDF:          v4.4.3
> I (451) heap_init: Initializing. RAM available for dynamic allocation:
> I (458) heap_init: At 3FCA63F8 len 00043318 (268 KiB): D/IRAM
> I (465) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
> I (472) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
> I (478) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
> I (485) spi_flash: detected chip: generic
> I (489) spi_flash: flash io: dio
> I (493) sleep: Configure to isolate all GPIO pins in sleep state
> I (500) sleep: Enable automatic switching of GPIO sleep configuration
> I (507) coexist: coexist rom version e7ae62f
> I (512) cpu_start: Starting scheduler on PRO CPU.
> I (0) cpu_start: Starting scheduler on APP CPU.
> I (10) esp_rmaker_console: Initialising UART on port 0
> I (532) esp_rmaker_commands: Registering command: up-time
> I (532) uart: queue free spaces: 8
> I (542) esp_rmaker_commands: Registering command: mem-dump
> I (552) esp_rmaker_commands: Registering command: task-dump
> I (552) esp_rmaker_commands: Registering command: cpu-dump
> I (562) esp_rmaker_commands: Registering command: sock-dump
> I (572) esp_rmaker_commands: Registering command: heap-trace
> I (572) esp_rmaker_commands: Registering command: reset-to-factory
> I (582) esp_rmaker_commands: Registering command: add-user
> I (592) esp_rmaker_commands: Registering command: get-node-id
> I (592) esp_rmaker_commands: Registering command: wifi-prov
> I (602) esp_rmaker_commands: Registering command: local-time
> I (602) esp_rmaker_commands: Registering command: tz-set
> I (612) esp_rmaker_commands: Registering command: cmd
> I (622) gpio: GPIO[2]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3
> E (632) gpio: gpio_install_isr_service(449): GPIO isr service already installed
> I (632) gpio: GPIO[4]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3
> I (642) gpio: GPIO[7]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
> I (652) gpio: GPIO[18]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
> I (662) led_serv: BLE led initialise...
> I (672) gpio: GPIO[1]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
> I (672) led_serv: BLE led initialise...
> I (682) gpio: GPIO[11]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
> I (692) led_serv: BLE led initialise...
> I (692) gpio: GPIO[19]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
> I (702) led_serv: BLE led initialise...
> I (712) gpio: GPIO[10]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
> I (722) led_serv: BLE led initialise...
> I (722) gpio: GPIO[6]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
> W (792) app_main: reading configuration from NVS
> W (792) app_main: reading end
> I (792) pp: pp rom version: e7ae62f
> I (792) net80211: net80211 rom version: e7ae62f
> I (802) wifi:wifi driver task: 3fcf7208, prio:23, stack:6656, core=0
> I (802) system_api: Base MAC address is not set
> I (802) system_api: read default base MAC address from EFUSE
> I (832) wifi:wifi firmware version: 8cb87ff
> I (832) wifi:wifi certification version: v7.0
> I (832) wifi:config NVS flash: enabled
> I (832) wifi:config nano formating: disabled
> I (832) wifi:Init data frame dynamic rx buffer num: 32
> I (842) wifi:Init management frame dynamic rx buffer num: 32
> I (842) wifi:Init management short buffer num: 32
> I (852) wifi:Init dynamic tx buffer num: 32
> I (852) wifi:Init static tx FG buffer num: 2
> I (862) wifi:Init static rx buffer size: 1600
> I (862) wifi:Init static rx buffer num: 10
> I (862) wifi:Init dynamic rx buffer num: 32
> I (872) wifi_init: rx ba win: 6
> I (872) wifi_init: tcpip mbox: 32
> I (882) wifi_init: udp mbox: 6
> I (882) wifi_init: tcp mbox: 6
> I (882) wifi_init: tcp tx win: 5744
> I (892) wifi_init: tcp rx win: 5744
> I (892) wifi_init: tcp mss: 1440
> I (902) wifi_init: WiFi IRAM OP enabled
> I (902) wifi_init: WiFi RX IRAM OP enabled
> I (922) esp_rmaker_work_queue: Work Queue created.
> I (942) esp_mqtt_glue: AWS PPI: ?Platform=APN3|A0|RM|EX00|RMDev|1x0|7CDFA1E25EA0
> I (942) esp_mqtt_glue: Initialising MQTT
> I (942) esp_rmaker_mqtt_budget: MQTT Budgeting initialised. Default: 100, Max: 1024, Revive count: 1, Revive period: 5
> I (952) app_main: RainMaker Initialised.
> I (952) esp_rmaker_node: Node ID ----- 7CDFA1E25EA0
> E (962) gpio: gpio_install_isr_service(449): GPIO isr service already installed
> I (972) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3
> I (1062) esp_rmaker_ota_using_topics: OTA enabled with Topics
> I (1072) esp_rmaker_ota: OTA state = 2
> I (1072) esp_rmaker_time_service: Time service enabled
> I (1082) esp_rmaker_time: Initializing SNTP. Using the SNTP server: pool.ntp.org
> W (1092) app_insights: Nodes with Self Claiming may not be accessible for Insights.
> I (1102) esp_insights: =========================================
> I (1102) esp_insights: Insights enabled for Node ID 7CDFA1E25EA0
> I (1112) esp_insights: =========================================
> I (1112) esp_rmaker_core: Starting RainMaker Work Queue task
> I (1122) esp_rmaker_work_queue: RainMaker Work Queue task started.
> W (1122) BT_INIT: esp_bt_mem_release not implemented, return OK
> I (1132) wifi_prov_scheme_ble: BT memory released
> I (1142) app_wifi: Already provisioned, starting Wi-Fi STA
> W (1152) BT_INIT: esp_bt_mem_release not implemented, return OK
> I (1152) wifi_prov_scheme_ble: BTDM memory released
> I (1162) esp_rmaker_local: Event 6
> I (1162) phy_init: phy_version 503,13653eb,Jun  1 2022,17:47:08
> I (1212) wifi:mode : sta (7c:df:a1:e2:5e:a0)
> I (1212) wifi:enable tsf
> I (1212) wifi:new:<1,0>, old:<1,0>, ap:<255,255>, sta:<1,0>, prof:1
> I (1222) wifi:state: init -> auth (b0)
> I (1222) wifi:state: auth -> assoc (0)
> I (1222) wifi:state: assoc -> run (10)
> W (1232) wifi:<ba-add>idx:0 (ifx:0, 70:f3:5a:74:6a:fd), tid:0, ssn:0, winSize:64
> I (1252) wifi:connected with Network_wifi, aid = 4, channel 1, BW20, bssid = 70:f3:5a:74:6a:fd
> I (1252) wifi:security: WPA2-PSK, phy: bgn, rssi: -41
> I (1262) wifi:pm start, type: 1
> 
> I (1262) wifi:set rx beacon pti, rx_bcn_pti: 14, bcn_timeout: 14, mt_pti: 25000, mt_time: 10000
> I (1292) wifi:BcnInt:102400, DTIM:1
> I (2292) app_wifi: Connected with IP Address:10.10.10.134
> I (2292) esp_netif_handlers: sta ip: 10.10.10.134, mask: 255.255.255.0, gw: 10.10.10.1
> I (2292) esp_rmaker_local: Starting ESP Local control with HTTP Transport and security version: 1
> I (2322) esp_https_server: Starting server
> I (2322) esp_https_server: Server listening on port 8080
> I (2322) esp_rmaker_local: esp_local_ctrl service started with name : 7CDFA1E25EA0
> W (2332) app_main: Unhandled RainMaker Event: 6
> I (2342) esp_mqtt_glue: Connecting to a1p72mufdu6064-ats.iot.us-east-1.amazonaws.com
> I (2342) esp_rmaker_core: Waiting for MQTT connection
> I (2822) esp-x509-crt-bundle: Certificate validated
> I (3232) esp_rmaker_time: SNTP Synchronised.
> I (3232) esp_rmaker_time: The current time is: Mon Jan 16 08:26:18 2023 +0100[CET], DST: No.
> I (4472) esp_mqtt_glue: MQTT Connected
> I (4472) app_main: MQTT Connected.
> I (4472) esp_rmaker_node_config: Reporting Node Configuration of length 5308 bytes.
> I (4792) esp_rmaker_param: Params MQTT Init done.
> I (4792) esp_rmaker_param: Reporting params (init): {"Brama":{"Name":"OUT1","Stan":0},"Furtka":{"Name":"OUT2","Stan":0,"Czas [s]":3},"Przycisk":{"Name":"INPUT","Stan":"ON","Min. czas pobudzenia [s]":0,"Powiadom gdy aktywne":false,"Powiadom gdy nieaktywne":false,"Odwroc logike":false},"MENU_SCAN":{"Wykryj nowe czujniki":false,"Usun wszystkie czujniki":false},"MENU_NODE":{"Nazwa urzadzenia":"Receiver","Ukryj komponent OUT 1":false,"Ukryj komponent OUT 2":false,"Ukryj komponent IN 1":false,"Zezw. użytk. na edycję":false},"SSDB6B0C232F46":{"Name":"Sensor(2F46)","Stan":"--","Wersja firmware":"--","MAC":"DB:6B:0C:23:2F:46","Model":"SNX-S-1","Bateria [%]":"--","Powiadom gdy ON":false,"Powiadom gdy OFF":false,"Usun ten czujnik":false,"Ukryj akcesorium":false},"Time":{"TZ":"Europe/Warsaw","TZ-POSIX":"CET-1CEST,M3.5.0,M10.5.0/3"},"Schedule":{"Schedules":[]},"Scenes":{"Scenes":[]},"Local Control":{"POP":"b167c722","Type":1}}
> I (4882) esp_rmaker_cmd_resp: Enabling Command-Response Module.
> I (4882) esp_rmaker_ota_using_topics: Subscribing to: node/7CDFA1E25EA0/otaurl
> I (4892) esp_insights: Scheduling Insights timer for 60 seconds.
> I (4992) app_main: MQTT Published. Msg id: 2812.
> I (5392) app_main: MQTT Published. Msg id: 23420.
> I (5392) app_main: MQTT Published. Msg id: 18803.
> I (9892) esp_rmaker_ota_using_topics: Fetching OTA details, if any.
> I (10182) app_main: MQTT Published. Msg id: 62926.
> ```

Do you see the device in the iOS / Android Rainmaker app?

**Comment by jacek12345** [comment]
Yes, I see.

**Comment by jacek12345** [comment]
This is some problem with my account i think.
I have two accounts for testing owner and user role app on two phones.
When I registered node (owned) on second account and logged in to Rainmaker dashboard and Insights dashboard, i see node (even in SELF CLAIMING). When back to first account and own node and logged in to dashboards, i can't see node.
More, this node is still visible on second account, where it was owned earlier. It is possible that i owned it on second account some time ago and that is why didn't see it on main account for some time. 
Shouldn't be node connected to ACTUAL owner account dashboards?

**Comment by shahpiyushv** [comment]
@jacek12345 , from your description, it seems there could indeed be an issue with the logic of primary user being assigned as admin for self claimed nodes. We will check this internally. We have also increased your quota as per the email. Sorry for the delay.
