### ISSUE TITLE
Rainmaker SDK building error! (MEGH-4155)

### ISSUE THREAD

**Issue by MahendraDnkTech** [espressif/esp-rainmaker#220]
Hello Geeks 
I hope all are doing well...
I have just configured the ESP32-IDF & rainmaker 
ESP32 IDF is successfully built while the rainmaker is causing the issue during the building!

I have followed the steps mentioned into the rainmaker getting started guide 

The error logs are attached here 
The error comes from the "esp-idf/esp_https_server" directory 

Pl. take a look in to it 

Thanks 

[err_logs.txt](https://github.com/espressif/esp-rainmaker/files/10341919/err_logs.txt)

**Comment by sanketwadekar** [comment]
Hi,
It seems like you are using IDF v5. Some changes have been made in rainmaker and IDF which is causing this error (this will be fixed soon). You can compile by using "release/v4.4" branch of IDF.

**Comment by MahendraDnkTech** [comment]
Oh! got it @sanketwadekar 
Many thanks 

Let me downgrade the version

Regards
MS

**Comment by MahendraDnkTech** [comment]
it's resolved by donwgrading the IDF version to v4.4

Thanks
