### ISSUE TITLE
Creating an task scheduler in rainmaker (MEGH-4208)

### ISSUE THREAD

**Issue by Vaibz97** [espressif/esp-rainmaker#228]
Hii,

 I am currently using ESP32WROOM and ESPrainmaker application. I have already scheduled an event in rainmaker but I want to run this same scheduled request after  (power comes back). I don't want to go for RTC and Battery.

**Comment by shahpiyushv** [comment]
All RainMaker schedules are stored in persistent memory and so, stay active even after a reboot, given that the local time is available via SNTP (which requires Internet). Is this what you are looking for?

**Comment by shahpiyushv** [comment]
Closing this issue since there was no further communication.
