### ISSUE TITLE
GPIO isr service already installed (MEGH-1277)

### ISSUE THREAD

**Issue by SNSIOTP** [espressif/esp-rainmaker#23]
Dear All,

I am getting the following warning/error when I flash and monitor on ESP32.

![Capture](https://user-images.githubusercontent.com/71267127/93295112-ed6d9f80-f809-11ea-9f47-38f4197e39ad.PNG)

I have used 8 GPIO pins of ESP32. 4 for output and 4 for input.

Seeking assistance please

**Comment by shahpiyushv** [comment]
@SNSIOTP , can you also share your code snippet indicating the GPIO numbers?

**Comment by SNSIOTP** [comment]
![image](https://user-images.githubusercontent.com/71267127/93426302-612aad80-f8d9-11ea-87d0-7a95bb2be70f.png)

**Comment by sachin0x18** [comment]
@SNSIOTP IO6-IO11 are connected to the on board SPI flash so they aren't available for general purpose usage. Please use some other GPIOs.

**Comment by SNSIOTP** [comment]
![image](https://user-images.githubusercontent.com/71267127/93464217-736f1080-f906-11ea-953c-41daf5b85e73.png)

**Comment by ameyinamdar** [comment]
Hi @SNSIOTP,
Please check which module you are using and refer to corresponding pin definition in the module datasheet. For example, if WROOM-32 module is being used, please refer to https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf

**Comment by sachin0x18** [comment]
Refer to section [3.2 External Flash and SRAM](https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf)

**Comment by SNSIOTP** [comment]
It seems I have to procure few genuine modules manufactured by Espressif to be able to test efficiently and will be more reliable. With these knock offs GPIO structure seems to be unreliable.

Thank you for all the suggestions and help. Issue can ne closed. Will test again and if the issue still persist will submit an issue.

**Comment by SNSIOTP** [comment]
Or maybe reopen the same issue.
