### ISSUE TITLE
Nova home top bar (MEGH-4291)

### ISSUE THREAD

**Issue by BigGDeX** [espressif/esp-rainmaker#235]
Hello, the top bar (where the system clock and notification lives) is white, like the texts and icons.

![698767FE-5E6D-472F-AE1A-F1DBF10CA2A6](https://user-images.githubusercontent.com/37479716/217163213-de709c3c-9d11-4564-b18f-9a3dbf84db43.jpeg)

Iphone 14 pro on iOS 16.2

**Comment by vikas-chandra-mnnit** [comment]
Hi @BigGDeX, this issue has been fixed in the Nova Home iOS App version 1.8.2 in App Store.
