### ISSUE TITLE
BUG or ERROR: User is not associated with any nodes (MEGH-4310)

### ISSUE THREAD

**Issue by CC-MASTER05** [espressif/esp-rainmaker#238]
Hello Giges,

I have issue with Rainmaker....i have add one LED with the ESP32S3 and loaded firmware of ESP-IDF along with Rainmaker but i am able to handle those led throw Mobile and Web Dashboard.

ISSUE: Once i try to update firmware over the air(OTA) at a time i am not able to see node with my account in cli throw can you help me to update firmware?

**Comment by sanketwadekar** [comment]
@CC-MASTER05 
Did you follow the steps mentioned [here](https://rainmaker.espressif.com/docs/get-started.html#get-started)? Also, did you see any error logs on the console? Please attach the error logs/screenshots.

**Comment by shahpiyushv** [comment]
Closing this issue as it seems to have been resolved.
