### ISSUE TITLE
ESP rainmaker app says " No internet connection" (MEGH-4377)

### ISSUE THREAD

**Issue by Jo14532** [espressif/esp-rainmaker#245]
### Answers checklist.

- [X] I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.
- [X] I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.
- [X] I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.

### General issue report

My ESP rainmaker app now continuously says "No internet connection" at the bottom of the screen. I can confirm I am connected to the internet and can watch youtube videos and use google.

Why do I only see this even though I can trigger my system using the on/off switch?

![image](https://user-images.githubusercontent.com/118254335/221677057-b1ef2a68-8ccd-4934-abda-8ba70cc6c022.png)

**Comment by khushbushah2302** [comment]
Please update the Android app to the current latest (2.10.1) and retry.

**Comment by Jo14532** [comment]
All fixed after the update thank you!

**Comment by bxslp** [comment]
Where is the Android app(2.10.1)?  Would you please give one. Thank you very much!

**Comment by khushbushah2302** [comment]
Hi @bxslp , 
ESP RainMaker Android app with version 2.10.1 is live on Google PlayStore. And code is available on GitHub latest release ([Release 2.10.1](https://github.com/espressif/esp-rainmaker-android/releases/tag/v2.10.1)).

**Comment by bxslp** [comment]
All fixed after the update. thanks !
