### ISSUE TITLE
Login from Swaggerapis as superadmin (private deployment) (MEGH-4441)

### ISSUE THREAD

**Issue by jacek12345** [espressif/esp-rainmaker#251]
### Answers checklist.

- [X] I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.
- [X] I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.
- [X] I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.

### General issue report

What credentials should I use on Swaggerapis for login as superadmin? I have private deployment.
I need to login and use API that need administrator permissions so can't use it when logged as user.

**Comment by shahpiyushv** [comment]
@jacek12345 , you must have received an email with super admin login credentials on the email address which was configured during deployment of the stack. Additionally, you will also have to put your Base URL as the API URL here:

![Screenshot 2023-03-20 at 4 41 01 PM](https://user-images.githubusercontent.com/8659527/226322989-69f39aed-a58e-4175-af83-97093b3ec1dd.png)

**Comment by jacek12345** [comment]
Thank You, it was related with using Login2, not Login API.
