### ISSUE TITLE
这个支持你们的esp-mdf么？ (MEGH-1408)

### ISSUE THREAD

**Issue by wanglemao** [espressif/esp-rainmaker#27]
如题，我如果采用你们的esp-mdf，可以采用这个方案连接到云和用APP控制么

**Comment by shahpiyushv** [comment]
@wanglemao , sorry for the very late reply. There are no plans of integrating this with esp-mdf as of now, but we may try to integrate this with [esp-mesh](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/mesh.html). But even that is not planned for the immediate future as of now.
