### ISSUE TITLE
Homekit example is not updated with latest fixes such as IRAM optimization fix for ESP32 to all examples (MEGH-4986)

### ISSUE THREAD

**Issue by adukale** [espressif/esp-rainmaker#282]
### Answers checklist.

- [X] I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.
- [X] I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.
- [X] I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.

### General issue report

If we compare homekit_switch example and multi_device, we can see that homekit example is not updated with latest fixes such as IRAM optimization fix for ESP32 to all examples commit c43cd07. Also if we compare examples, there are some features also missing from homekit_switch example like Scheduling and Scenes support.

**Comment by vikramdattu** [comment]
> If we compare homekit_switch example and multi_device, we can see that homekit example is not updated with latest fixes such as IRAM optimization fix for ESP32 to all examples commit https://github.com/espressif/esp-rainmaker/commit/c43cd071faf5be97a37057aed75baa3016164846.

@adukale the IRAM optimisations fix is already part of the `homekit_switch` example and hence, the above commit doesn't do it.

> Also if we compare examples, there are some features also missing from homekit_switch example like Scheduling and Scenes support.

Thanks for the heads up. For now, you may refer other examples to for schedule and scenes support.
