### ISSUE TITLE
RainMaker on ESP32 (MEGH-816)

### ISSUE THREAD

**Issue by AleConti** [espressif/esp-rainmaker#3]
Hi, I build and flash firmware to an ESP32WROOM, and get this error:

E (824) esp_rmaker_core: Failed to initialise Node Id
E (824) app_main: Could not initialise ESP RainMaker. Aborting!!!

This is Switch example, it build OK and then flash OK too. BOOT and Led output are ok too, it turn ON and OFF the output led. But WiFi dont start .

Thanks!!!
Ale Conti

**Comment by scamberlin** [comment]
I tried with this type of problem on an m5stack. I think the support for esp32 card is incomplete ? There are problems with retrieving the node id on esp32 (it's work with esp32s2) and with claiming support ?

**Comment by shahpiyushv** [comment]
We will start giving out support for ESP32 on-demand and later open up to a wider audience. Can you send the email id you used for registering on ESP RainMaker to esp-rainmaker-admin@espressif.com?

**Comment by AleConti** [comment]
> I tried with this type of problem on an m5stack. I think the support for esp32 card is incomplete ? There are problems with retrieving the node id on esp32 (it's work with esp32s2) and with claiming support ?

Yes, sure, I advanced one more step, and now it creates NODE ID , but fails when claim MQTT Credentials... 
I (851) wifi:Init dynamic rx buffer num: 32
I (881) esp_rmaker_core: Node ID ----- 30AEA40CA360
E (881) esp_rmaker_core: Failed to initialise MQTT Config. Credentials missing.
E (881) app_main: Could not initialise ESP RainMaker. Aborting!!!

**Comment by scamberlin** [comment]
The code actually generate certificates for esp32s2 but not for esp32. It seem to be in progress :)

**Comment by AleConti** [comment]
Yes, self claiming service is only for esp32s2 now, we must wait for our esp32 ;) ...

**Comment by scamberlin** [comment]
Or we can provide some help... This project is great !

**Comment by AleConti** [comment]
Yes of course! In the menuconfig of ESP32s2 the self claim option appears to setup, where the URL and the Host MQTT endpoint are configured to generate the MQTT certificate. Very interesting project, I have a batch of esp32WROOM to apply it, and the application is very interesting as presented. I'm working with AWS free trier for the backend, and AWS amplify with React Native for the App, but this project directly saves me a lot of time and cost.
