### ISSUE TITLE
[esp rainmaker component] Build error with unkown type 'time_t' (MEGH-5274)

### ISSUE THREAD

**Issue by lijunru-hub** [espressif/esp-rainmaker#300]
### Answers checklist.

- [X] I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.
- [X] I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.
- [X] I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.

### IDF / ESP32-Arduino version.

IDF release/v5.2

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### Development Kit.

ESP32S3

### What is the expected behavior?

Build Success.

### What is the actual behavior?

![企业微信截图_17073613151068](https://github.com/espressif/esp-rainmaker/assets/68437239/985fda63-b56c-4d29-a5be-d5ea5739078c)

### Steps to reproduce.

Pull esp_rainmaker:v1.1.0, then build.

You should add #include <time.h> in the header file where you are using time_t.

**Comment by lijunru-hub** [comment]
If this issue has been resolved, please let me know.

**Comment by shahpiyushv** [comment]
The issue is fixed in the SDK itself in https://github.com/espressif/esp-rainmaker/commit/7d4c1e36f9110e04c30c21a708762ed91eea99ac, but the component had not been updated. We will do it with some other change soon enough.

**Comment by lijunru-hub** [comment]
Thank for this.
