### ISSUE TITLE
Inserting a '-' character in the device name causes failure in get simple TS data. (MEGH-5347)

### ISSUE THREAD

**Issue by kongshuiJ** [espressif/esp-rainmaker#304]
### Answers checklist.

- [X] I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.
- [X] I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.
- [X] I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.

### General issue report

**idf: V5.2**
**rainmaker: 909c7f00be0cd3343ba18a174d403889f0ea314b**

**esp_rmaker_device_create**() function's first parameter contains a **'-'** character. ex: light-dev
Device parameters are set as properties (**PROP_FLAG_READ | PROP_FLAG_SIMPLE_TIME_SERIES**).
Wi-Fi connection is successful, and the device is displayed on the device end.

```
I (246926) esp_rmaker_param: Reporting Simple Time Series Data for light-dev.temp
I (246936) esp_rmaker_param: Reporting params: {"light-dev":{"temp":-68}}
```
When using **Swagger UI** to get Simple Time Series Data, all parameters are correctly set. However, the server returns the following response.

```
{
  "status": "failure",
  "description": "Error getting data from DB. Please try after some time",
  "error_code": 136003
}
```

Removing the '-' character from the device name resolves the issue, and everything is working correctly. ex: lightdev
So, does that mean Rainmaker currently does not support the '-' character?

**Comment by shahpiyushv** [comment]
Sorry for the delay in updating here, but this issue was fixed in our backend release of April 2024
