### ISSUE TITLE
Time Zone setting in the device (MEGH-1516)

### ISSUE THREAD

**Issue by sivansanthoshd** [espressif/esp-rainmaker#31]
I am trying to set the time zone for my device as IST by editing the code as per the documentation - https://rainmaker.espressif.com/docs/time-service.html#time-service. 

First i tried to add the following timezone region:
>const char *tz = "Asia/Kolkata";
>esp_err_t esp_rmaker_time_set_timezone(*tz);

and the second one using the posix timezone:

>const char *tz_posix = "IST-5:30";
>esp_err_t esp_rmaker_time_set_timezone_posix(*tz_posix);

both throw the error 

>"../main/app_main.c: In function 'app_main':
../main/app_main.c:161:44: error: expected declaration specifiers or '...' before '*' token
     esp_err_t esp_rmaker_time_set_timezone(*tz);
                                            ^
[1212/1219] Linking CXX static library esp-idf\esp_rainmaker\libesp_rainmaker.a
ninja: build stopped: subcommand failed.
ninja failed with exit code 1"

Tried with the code,

>const char *tz = "Asia/Kolkata";
>esp_err_t esp_rmaker_timezone_service_enable(void);
>esp_err_t esp_rmaker_time_set_timezone(tz);

throwing the warning 

>[1212/1219] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj
../main/app_main.c: In function 'app_main':
../main/app_main.c:162:5: warning: parameter names (without types) in function declaration
     esp_err_t esp_rmaker_time_set_timezone(tz);
     ^~~~~~~~~

What is the issue here? If not Am i doing this in a wrong manner?

**Comment by shahpiyushv** [comment]
@sivansanthoshd the primary culprit here is the `esp_err_t` preceding the function call. `esp_err_t` is just the return type for the functions. You have to simply call the function like this:

```c
esp_rmaker_time_set_timezone("Asia/Kolkata");
```

**Comment by sivansanthoshd** [comment]
After changing it to this

>esp_rmaker_time_set_timezone("Asia/Kolkata");

>I get this error

>../main/app_main.c: In function 'app_main':
../main/app_main.c:159:5: error: implicit declaration of function 'esp_rmaker_time_set_timezone'; did you mean 'esp_rmaker_node_get_info'? [-Werror=implicit-function-declaration]
     esp_rmaker_time_set_timezone(&timezone);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
     esp_rmaker_node_get_info
cc1.exe: some warnings being treated as errors
[1212/1219] Linking CXX static library esp-idf\esp_rainmaker\libesp_rainmaker.a
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by shahpiyushv** [comment]
@sivansanthoshd to use the `esp_rmaker_time_set_timezone ()` function, you have to include the  `esp_rmaker_utils.h` file in your code.

**Comment by sivansanthoshd** [comment]
@shahpiyushv that worked like a breeze. Thank you.

**Comment by shahpiyushv** [comment]
Closing this issue since it has been addressed.
