### ISSUE TITLE
Get internet data from gsm module to run rainmaker  (MEGH-5827)

### ISSUE THREAD

**Issue by nravin5** [espressif/esp-rainmaker#321]
### Is your feature request related to a problem?

Is it possible to run rainmaker gsm module gprs data please suggest.

**Comment by shahpiyushv** [comment]
Most of the RainMaker logic is independent of the underlying transport layer. So if you have a clean integration with gsm module for any esp idf examples that use the network interface (esp_netif), using RainMaker should be possible. However, the user-node association that happens during Wi-Fi provisioning needs to be looked into.

**Comment by shahpiyushv** [comment]
Closing this issue. Please file a new one if some specific info is required in this context.
