### ISSUE TITLE
Matter controller Building failed

### ISSUE THREAD

**Issue by aadhimellow** [espressif/esp-rainmaker#335]
### Answers checklist.

- [X] I have read the [Rainmaker documentation](https://rainmaker.espressif.com/docs/get-started.html) and the issue is not addressed there.
- [X] I have updated my IDF branch (release/vX.Y) to the latest version and checked that the issue is present there. This is not applicable if you are using Rainmaker with Arduino.
- [X] I have searched the [Rainmaker forum](https://www.esp32.com/viewforum.php?f=41) and issue tracker for a similar issue and not found a similar issue.

### IDF / ESP32-Arduino version.

v5.2.2

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### Development Kit.

ESP32S3 BOX 3

### What is the expected behavior?

I am trying to build the Matter + Rainmaker Controller With Touchscreen Example [https://github.com/espressif/esp-rainmaker/tree/master/examples/matter/matter_controller_with_touchscreen](url).
Followed everything based on the instructions given.
The program is supposed to be build into a build file which later needs to be flashed into the ESP32S3 BOX.

### What is the actual behavior?

When i execute the command idf.py build. It is showing an error 
esp-rainmaker/examples/matter/matter_controller_with_touchscreen/main/app_matter_ctrl.cpp:13:10: fatal error: DataModelLogger.h: No such file or directory
esp-rainmaker/examples/matter/matter_controller_with_touchscreen/main/app_matter_ctrl.cpp:13:10: fatal error: DataModelLogger.h: No such file or directory
The build is getting failed

### Steps to reproduce.

1. Cloned the repository for idf v2.2 and installed it on mac os using install.sh command.
2. Executed export.sh script for idf
3.Cloned esp-matter [https://github.com/espressif/esp-matter](url) and ran install.sh and export.sh
4. Cloned rainmaker SDK [https://github.com/espressif/esp-rainmaker](url)
5. Added esp_secure_cert_mgr [https://components.espressif.com/components/espressif/esp_secure_cert_mgr](url)  by executing the command idf.py add-dependency `"espressif/esp_secure_cert_mgr^2.4.1"` on the project directory
6. To claim the certificate I have opened the $RMAKER_PATH/cli directory
7. `./rainmaker.py claim --matter <port>` this command didnt work because the rainmaker.py is inside another folder inside the cli folder:`$RMAKER_PATH/cli/rainmaker/rainmaker.py`
8. Executed `pip install esp-matter-mfg-tool` command
9. Executed `esp-matter-mfg-tool -v 0x131B -p 0x2 -cd $RMAKER_PATH/examples/matter/mfg/cd_131B_0002.der --csv $RMAKER_PATH/examples/matter/mfg/keys.csv --mcsv $RMAKER_PATH/examples/matter/mfg/master.csv` mentioned in the README.md of matter controller with touchscreen example which generated nodeId
10. Added nodeId and executed the command `esptool.py write_flash 0x3e0000 out/131b_2/<node-id>/<node-id>-partition.bin
 `
11. Executed each commands mentioned in  Building the example of README.md but failed to build it.

### Build Logs.

```plain
I was not able to add the whole log so pasting the link of the log here 
[https://nopaste.net/x5I5OkrqqC](url)

This is the error that I got

/Users/a1248986/matterProject/esp-rainmaker/examples/matter/matter_controller_with_touchscreen/main/app_matter_ctrl.cpp:13:10: fatal error: DataModelLogger.h: No such file or directory
   13 | #include <DataModelLogger.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
[1838/1878] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/app_main.cpp.obj
[1839/1878] Linking C static library esp-idf/esp_matter/libesp_matter.a
[1840/1878] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/app_matter_controller.cpp.obj
[1841/1878] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/app_driver.cpp.obj
[1842/1878] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/controller_ctrl.cpp.obj
ninja: build stopped: subcommand failed.
[0;33mBUG: component_requirements.py: cannot match original component filename for source component main[0m
ninja failed with exit code 1, output of the command is in the /Users/a1248986/matterProject/esp-rainmaker/examples/matter/matter_controller_with_touchscreen/build/log/idf_py_stderr_output_74952 and /Users/a1248986/matterProject/esp-rainmaker/examples/matter/matter_controller_with_touchscreen/build/log/idf_py_stdout_output_74952
```

### More Information.

I was not able to add the whole log so pasting the link of the log here 
[https://nopaste.net/x5I5OkrqqC](url)

**Comment by vikramdattu** [comment]
@aadhimellow  can you please check with the particular commit of sep-matter mentioned [here](https://github.com/espressif/esp-rainmaker/tree/master/examples/matter#prerequisites)?
