### ISSUE TITLE
Alexa skill in Italy (MEGH-1585)

### ISSUE THREAD

**Issue by iz0eyj** [espressif/esp-rainmaker#37]
Hi guys,
first of all congratulations for the fantastic job you are doing.
Please note that the Alexa skill is not available in Italy, which makes it a bit problematic to use this system outside of simple tests.
Would it be possible to solve the problem?

 Thanks, Federico

**Comment by shahpiyushv** [comment]
@iz0eyj, thanks for reporting this. We will check and get this resolved as soon as possible.

**Comment by iz0eyj** [comment]
Thanks @shahpiyushv , if you need help translating the skill into Italian (I don't think it's mandatory), just ask.

**Comment by iz0eyj** [comment]
@shahpiyushv hi, still disabled for our country.

![Screenshot_20210104-134705](https://user-images.githubusercontent.com/6331284/103536933-a9bfa400-4e93-11eb-99a2-ad929c29fce1.jpg)

**Comment by iz0eyj** [comment]
![Uploading Screenshot_20210104-135143.jpg…]()

**Comment by iz0eyj** [comment]
@shahpiyushv Hello, still unaivalable in our country.

![Screenshot_20210104-135143](https://user-images.githubusercontent.com/6331284/103537285-716c9580-4e94-11eb-8f91-ff868bc93323.jpg)

**Comment by shahpiyushv** [comment]
@iz0eyj , we are almost done with support for additional languages as well as support for some additional device categories. Once the skill re-certification is done, I will give an update here. Thanks for your patience!

**Comment by iz0eyj** [comment]
Thanks @shahpiyushv

**Comment by shahpiyushv** [comment]
@iz0eyj, the skill should now be available in your region and language. Can you check?

**Comment by shahpiyushv** [comment]
Closing this issue since this has been resolved. Do let us know if you are still facing the problem.
