### ISSUE TITLE
[Check node error] API Defintions for Rainmaker Backend Service (MEGH-1598)

### ISSUE THREAD

**Issue by victorK8** [espressif/esp-rainmaker#39]
Hi, 

I'm developing my own web service based on ESP Rainmaker API. I'm with Swagger API, Version 1 (v1) 
The next link shows info. about API: https://swaggerapis.rainmaker.espressif.com/#/

I can login and keep active the login without problems. Next lines show url and succesful logs.

**URL**: 
 _https://api.rainmaker.espressif.com/v1/login_

**LOGS**: 
        _{
          "status": "success",
          "description": "Login successful",
          "idtoken": "idtoken",
          "accesstoken": "accesstoken",
          "refreshtoken": "refreshtoken"
       }_

However, when I try to access the params from a node, it returns errors. Next lines show url and logs.

**URL**: 
_https://api.rainmaker.espressif.com/v1/user/nodes/params?nodeid=[NodeIdValue]_

**LOGS**: 
_{
  "status": "failure",
  "description": "Unauthorized"
}_

I don't know what it's happening. Does anyone work with Rainmaker API? Thanks!

Victor

**Comment by dattatrayhkulkarni-espressif** [comment]
Hi Victor, 

The Get Node Parameters API is an authenticated API.
After you successfully login, you will get the accesstoken in the response.

For calling the Rainmaker authenticated APIs, you will need to pass this access token as the Authorization  parameter in the HTTP header.

e.g. if you are using Postman as the REST client, you will need to populate the value of Access token in the Authorization HTTP header.

Similarly if you are building some Web apps or Mobile Apps, you will need to use this Access token in the HTTP Authorization 
header.

Hope this addresses your issue.

regards,
dattatray.

<img width="693" alt="Screenshot 2020-12-17 at 5 41 19 PM" src="https://user-images.githubusercontent.com/57657471/102486495-1f073880-408f-11eb-8609-78b0b9c019d3.png">

**Comment by victorK8** [comment]
Hi dattatray,

I have added Access Token Value to headers in GET request and it is working. 

Thank dattatray!

Regards,
Victor

**Comment by bbinet** [comment]
Hey @victorK8, I'm also interested in an opensource implementation of the rainmaker backend API.
I have planned to work on this, but I haven't found the time to start it yet.

Do you envision to release your implementation of these webservices as opensource software? I may give a hand depending on the language and technologies you've chosen.

**Comment by victorK8** [comment]
Hi @bbinet , 

I can't share the code of application because it's for a service from a business. Only I can share that is for an Alexa Skill and it will be developed in Javascript.

Regards

Victor

**Comment by bbinet** [comment]
Ok no problem @victorK8
