### ISSUE TITLE
Question: what is the `sec_cert` partition (type=0x3F) (MEGH-1665)

### ISSUE THREAD

**Issue by bbinet** [espressif/esp-rainmaker#40]
I see the following line in `partitions.csv`:
```
sec_cert,  0x3F, ,0xd000,    0x3000, ,  # Never mark this as an encrypted partition
```
So what is this `sec_cert` partition?

**Comment by bbinet** [comment]
And can we safely remove this partition?

**Comment by shahpiyushv** [comment]
@bbinet That's there to keep it compatible with some of our other services. It isn't being used anywhere in RainMaker though, and you may remove it.

**Comment by bbinet** [comment]
@shahpiyushv Ok, thank you
