### ISSUE TITLE
warning: passing argument 3 of 'esp_event_handler_register' from incompatible pointer type (MEGH-1954)

### ISSUE THREAD

**Issue by jjsch-dev** [espressif/esp-rainmaker#55]
The previous warning is generated in a compilation for esp32-c3, my solution was to cast a void *: 
esp_event_handler_unregister (WIFI_PROV_EVENT, WIFI_PROV_INIT, (void*) &event_handler);

**Comment by shahpiyushv** [comment]
@jjsch-dev , the warnings have been fixed.
