### ISSUE TITLE
Documentation Correction Request (MEGH-2072)

### ISSUE THREAD

**Issue by JohnMacrae** [espressif/esp-rainmaker#63]
https://rainmaker.espressif.com/docs/ota.html

Please amend the code reuired for OTA to include:

        .server_cert = ESP_RMAKER_OTA_DEFAULT_SERVER_CERT,

rather than the current:

     .server_cert = (char *)ota_server_cert,

which does not work (or should mention the use of the default server cert)

**Comment by shahpiyushv** [comment]
Thanks for reporting. The docs are now corrected.
