### ISSUE TITLE
Impossible to delete first/last node (MEGH-2078)

### ISSUE THREAD

**Issue by JohnMacrae** [espressif/esp-rainmaker#65]
There seems to be no way of deleting the first node created on the dashboard.  Deleting from the phone app still leaves the node listed. There is no button on the dashboard to remove the last instance.

**Comment by shahpiyushv** [comment]
@JohnMacrae , the nodes you see on dashboard and the ones you see in the phone app are actually "admin" and "end user" views respectively. End user association can be removed, but the admin user association with a node id stays for lifetime. Please check out the docs here to understand these user-roles.

Note that if some other user claims the same node (basically the same mac address), a new node id gets assigned for that user:mac combination. The old entry for the old user will still stay as it is.

**Comment by JohnMacrae** [comment]
OK - I understand - many thanks for explaining :)

**Comment by shahpiyushv** [comment]
Closing this issue since it has been answered.
