### ISSUE TITLE
Turning on a LED for factory_reset_indicate function (MEGH-2141)

### ISSUE THREAD

**Issue by alexiskyriakou** [espressif/esp-rainmaker#67]
Hello guys,

I add an LED indicator, for visual purpose, when the "Release button to trigger factory reset." is show up in the serial monitor as below but nothing happens

```
static void factory_reset_indicate(void *arg)
{
   ESP_LOGI(TAG, "Release button to trigger factory reset.");

    gpio_set_direction(GPIO_NUM_9, GPIO_MODE_OUTPUT);
    gpio_set_level(GPIO_NUM_9, 1);
    vTaskDelay(1000 / portTICK_RATE_MS);

}
```

The led is fully functional

The consept is give to users visualy the response when they must release the button

Any suggestion?

Thank you
Alexis

**Comment by shahpiyushv** [comment]
@alexiskyriakou , I tried this attached patch on switch example and the LED connected to pin 16 indeed worked as expected, i.e. turned on to indicate that the button can now be released. Can you check it out?
[reset_led_patch.txt](https://github.com/espressif/esp-rainmaker/files/6495605/reset_led_patch.txt)
