### ISSUE TITLE
Feature request: schedule a light/deep sleep (MEGH-2200)

### ISSUE THREAD

**Issue by bbinet** [espressif/esp-rainmaker#70]
It would be great if rainmaker could provide a way to schedule light or deep sleep to save energy.

We could for example ask a rainmaker device to sleep during a custom duration, or ask it to sleep until a custom wake-up date.

Would you plan to support such a feature, and if yes, what would be the ETA?

Thanks for this great framework!

**Comment by shahpiyushv** [comment]
@bbinet , this would be too specific. Would it rather be possible to create a parameter for that and use the current scheduling mechanism?

**Comment by bbinet** [comment]
@shahpiyushv thank you for your answer.
Yes, you're right, I can create a dedicated parameter for that.
