### ISSUE TITLE
homekit_switch  Please set HOMEKIT_PATH to esp-homekit-sdk repo (MEGH-2267)

### ISSUE THREAD

**Issue by oksimple** [espressif/esp-rainmaker#76]
![image](https://user-images.githubusercontent.com/10106142/120594431-85ccb280-c473-11eb-9e9d-ff0f76791d32.png)

What is causing this problem?

**Comment by shahpiyushv** [comment]
@oksimple Since you are trying to compile the homekit_switch example, you would indeed also require the [esp-homekit-sdk](https://github.com/espressif/esp-homekit-sdk) repo. Have you followed the instructions in this example's [README](https://github.com/espressif/esp-rainmaker/tree/master/examples/homekit_switch)?

**Comment by oksimple** [comment]
@shahpiyushv Yes, I strictly follow the documentation to compile, and I can compile several other examples successfully, but the compilation of homekit_switch fails.

**Comment by shahpiyushv** [comment]
@oksimple , none of the other examples require the esp-homekit-sdk, so they are expected to compile withoit requiring any additional setup. Have you explicitly followed these steps as per above mentioned [README](https://github.com/espressif/esp-rainmaker/blob/master/examples/homekit_switch/README.md)?

## Setup

Compiling this example would need the [esp-homekit-sdk](https://github.com/espressif/esp-homekit-sdk) repository. Clone it at a suitable location using:

```
git clone --recursive https://github.com/espressif/esp-homekit-sdk.git
```

Export the path to this repository using:

```
export HOMEKIT_PATH=/path/to/esp-homekit-sdk/
```

**Comment by oksimple** [comment]
@shahpiyushv  thank you for your answer, I will try it later, and finally, can I use esp-rainmaker commercially?

**Comment by shahpiyushv** [comment]
@oksimple , sorry I forgot to reply to your second query. The public RainMaker is not allowed to be used for commercial purposes, but we do have commercial variants of ESP RainMaker. Please send an email to sales@espressif.com for more info.

**Comment by shahpiyushv** [comment]
Closing this issue as appropriate answer has been provided.

**Comment by jacek12345** [comment]
Where (from what path) should i start for typing "export HOMEKIT_PATH=/path/to/esp-homekit-sdk/" ? I can only from F:/GitHub/esp-idf. But it seems to not work:
`F:\GitHub\esp-idf>export HOMEKIT_PATH=\GitHub\esp-homekit-sdk
Setting IDF_PATH: F:\GitHub\esp-idf`
When I try from other locations (e.g. from "F:\GitHub\esp-homekit-sdk" i see error that "'export' is not recognized as an internal or external command, operable program or batch file.". 
I got stuck...
