### ISSUE TITLE
Pop contains invalid chars while provisioning in HomeKit Example (MEGH-2323)

### ISSUE THREAD

**Issue by adukale** [espressif/esp-rainmaker#78]
Development Kit: ESP32-DevKitC
Kit version (for WroverKit/PicoKit/DevKitC): DevKitv1
Module or chip used: ESP32-WROOM-32
IDF version (run git describe --tags to find it):
v4.2
Build System: idf.py
Compiler version (run xtensa-esp32-elf-gcc --version to find it):
8.4.0
Operating System: Windows
(Windows only) environment type: PowerShell
Using an IDE?: No
Power Supply: USB

Pop contains invalid chars while provisioning in HomeKit Example.
Ex.:
https://rainmaker.espressif.com/qrcode.html?data={"ver":"v1","name":"PROV_8BEA1C","pop":"���X57�g","transport":"softap"}
I (1720) app_wifi: Provisioning Started. Name : PROV_8BEA1C, POP : ���X57�g

![image](https://user-images.githubusercontent.com/1003980/121812047-09f91400-cc84-11eb-841e-adb2dcec59a0.png)

**Comment by adukale** [comment]
This issue is still there.
Any help is appreciated.
![image](https://user-images.githubusercontent.com/1003980/127687405-817e70bd-b1e6-4d71-9be6-714e56604a3b.png)

**Comment by shahpiyushv** [comment]
@adukale , we plan to make some more changes to the wifi code in HomeKit, but for the time being, you can use this patch:
[homekit_wifi_patch.txt](https://github.com/espressif/esp-rainmaker/files/6909119/homekit_wifi_patch.txt)

Apply using:

```
git apply homekit_wifi_patch.txt
```

**Comment by adukale** [comment]
@shahpiyushv Awesome. This fixed the issue.
The homekit code seems bit complicated to me but considering functionality it is worth diving into.
Cheers...!
Thanks. Appreciate your help.
