### ISSUE TITLE
Can we execute RAINMAKER SWITCH code on ESP32 using WLAN (local network without internet) (MEGH-2650)

### ISSUE THREAD

**Issue by ajarsco** [espressif/esp-rainmaker#89]

**Comment by shahpiyushv** [comment]
@ajarsco , the question is not clear to me. Once a device has been added to RainMaker, it can later be controlled on the local network even when there is no Internet. Check the docs [here](https://rainmaker.espressif.com/docs/local-control.html) for more info.

**Comment by ajarsco** [comment]
> @ajarsco , the question is not clear to me. Once a device has been added to RainMaker, it can later be controlled on the local network even when there is no Internet. Check the docs [here](https://rainmaker.espressif.com/docs/local-control.html) for more info.

Ok thank you sir, let me check

**Comment by shahpiyushv** [comment]
Closing this issue since it has been addressed. Do let us know if any additional information is required.
