### ISSUE TITLE
Scheduling not supported in homekit_example (MEGH-2718)

### ISSUE THREAD

**Issue by adukale** [espressif/esp-rainmaker#94]
Hi

Is there any specific reason scheduling is not supported in homekit_example.
Or do I need to enable some flag to enable scheduling?

Thanks in advance.

**Comment by shahpiyushv** [comment]
Scheduling is an optional feature and not relevant not directly relevant in the context of a demo app that's primarily to show how RainMaker + HomeKit works together. That's the only reason why it's not there. You can read the docs [here] (https://rainmaker.espressif.com/docs/scheduling.html#usage) or copy relevant code from any of the examples (including timezone related code) and enable scheduling.

**Comment by adukale** [comment]
@shahpiyushv Noted. Will check.
Thanks for the information.
