### ISSUE TITLE
Is it possible to use UART pins of ESP-32 C3 mini-1 as a general GPIO as well as UART pin for debugging purpose simultaneously. Also whether JTAG pins can be used for debugging as well as general GPIO at the same time. And if it is possible then how to do so.

### ISSUE THREAD

**Issue by Shravani100** [espressif/esp-rainmaker#99]
I want to know, is it possible to use UART pins of ESP-32 C3 mini-1 as a general GPIO as well as UART pin for debugging purpose simultaneously. Also whether JTAG pins can be used for debugging as well as general GPIO at the same time. And if it is possible then how to do so.

**Comment by shahpiyushv** [comment]
@Shravani100 , sorry for the late reply, but it would be better if you ask this under [esp-idf issues](https://github.com/espressif/esp-idf/issues).

**Comment by felixcollins** [comment]
This issue should be closed.
